// TEMPORARY static analyst-sentiment summaries, one succinct plain-language line per holding.
//
// These are meant to be generated by Claude from the Finnhub analyst consensus + that day's
// Daily Briefing agent research, but the Dartmouth LLM gateway is out of credits right now, so
// this hand-authored snapshot (as of the 2026-07-30 agent run) stands in for the live call.
//
// TODO(analyst-summary): replace this map with a server route that prompts the Dartmouth Claude
// per stock (recommendation-trends consensus + the Turso `assets` rationale/signals) and caches
// the result per (ticker, researched_at). No em dashes, no links, plain language.

export const ANALYST_SUMMARIES: Record<string, string> = {
  AAPL: "Analysts are broadly positive, with far more buy ratings than holds and almost no sell calls. The stock just touched a record high, so tonight's earnings carry a high bar.",
  AMD: "Analysts lean clearly bullish. Shares fell hard in this week's chip selloff, and expectations are high heading into the August 4 earnings report.",
  AMZN: "Analysts are strongly positive, almost entirely buy ratings. Amazon reports tonight, with cloud growth the number that matters most.",
  AVGO: "Analysts are very bullish. Broadcom rides the same AI buildout as Nvidia and does not report until September, so there is no near-term earnings risk.",
  DIS: "Analysts still lean positive despite a rough stretch. Disney reports next week against a run of small setbacks, cushioned by its parks and holiday film slate.",
  F: "Analysts are neutral, with most rating Ford a hold. Its results are the first real test of profits without last quarter's one-time tariff gain.",
  GM: "Analysts lean positive. GM sits near a record high after beating earnings and raising its outlook, and it is insulated from the tech and chip selloff.",
  GOOG: "Analysts are broadly positive. Alphabet's earnings are behind it, so it now moves mostly with the big tech group and this week's cloud updates.",
  GOOGL: "Analysts are broadly positive. Alphabet's earnings are behind it, so it now moves mostly with the big tech group and this week's cloud updates.",
  KOP: "The small group of analysts covering it is positive. Koppers is a thinly traded industrial materials company that reports on August 6.",
  LLY: "Analysts are bullish. Strong demand for its weight-loss and diabetes drugs has pushed the stock near record highs ahead of its early August report.",
  MA: "Analysts are strongly positive. Mastercard is a steady non-tech holding, with cross-border spending the thing to watch when it reports Thursday.",
  META: "Analysts are clearly bullish. Meta's ad engine is strong but profit growth is thin as AI costs rise, and its spending plans are the focus.",
  MSFT: "Analysts are very bullish, and sentiment just improved after a blowout quarter. Cloud growth accelerated and the results eased fears about heavy AI spending.",
  MU: "Analysts stay bullish even though Micron sits at the center of the memory-chip selloff and has slid into a bear market. It does not report until September.",
  NVDA: "Analysts are strongly bullish. Nvidia had a rough week in the chip selloff, but Microsoft's blowout suggests AI demand is not slowing.",
  SHEL: "Analysts lean positive. Shell posted its best profit since 2022 and kept buying back stock, helped by rising oil prices.",
  SPCX: "Analysts lean bullish for a newly public name. SpaceX trades below its IPO price ahead of its first earnings on August 4 and a large insider share unlock two days later.",
  TSLA: "Analysts are mixed, with holds nearly matching buys and a rare handful of sell calls. Tesla just had its worst week since 2022 and has no growth catalyst until fall deliveries.",
  RIVN: "Analysts are mixed on Rivian, with a fair number of holds and a few sell calls alongside the buys, reflecting an unprofitable EV maker still scaling up.",
  ABNB: "Analysts are split fairly evenly between buy and hold on Airbnb, so the consensus is only mildly positive.",
  ORCL: "Analysts are clearly positive on Oracle, drawn by its growing cloud and AI infrastructure business.",
};
